filebeat.inputs:
  - type: log
    enabled: true
    paths:
      - /var/log/test_json/generate.json
    fields:
      service: custom_metrics_app

  - type: log
    enabled: true
    paths:
      - /host_metrics_app/host_metrics_app.log
    fields:
      service: host_metrics_app

output.logstash:
  hosts: ["logstash:5044"]
